### ISSUE TITLE
macOS Catalina

### ISSUE THREAD

**Issue by jooplaan** [errata-ai/vale-server#11]
When trying to open the application for the first time on a Mac with macOS Catalina 10.15.1, there is an error message saying: "Vale Server.app” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information." 

Any update in the pipe-line for macOS that fixes this? 

![Screen Shot 2019-11-14 at 17 45 09](https://user-images.githubusercontent.com/214447/68877873-0fd4ef00-0707-11ea-87a7-b980464084d8.png)

**Comment by jdkato** [comment]
Yes, the next release will be compatible with 10.15; I'll close this issue once I've updated the download links.

**Comment by jdkato** [comment]
This should be resolved now.
