### ISSUE TITLE
Error activating

### ISSUE THREAD

**Issue by ChrisChinchilla** [errata-ai/vale-server#14]
I'm not even sure that this repo is the best place to open issues, but here we go.

I opened Vale server today and it was no longer activated, I added my key and got the error:

> Stopped (quota reached).

Any ideas?

**Comment by jdkato** [comment]
What version (you can find this from the menu bar -> About) are you using?

I believe this error should be fixed in v1.4, which you can download from your Gumroad account (your configuration/settings will carry over as well).

**Comment by ChrisChinchilla** [comment]
Hmm, I have 1.3, but I don't have a Gum road login as far as I know. But I'll dig further.

**Comment by ChrisChinchilla** [comment]
Recovered my account, updated, it works!
