### ISSUE TITLE
Local maintainable rule repository

### ISSUE THREAD

**Issue by lexkazakov** [errata-ai/vale-server#16]
Hi! 

Can you please add an ability to load and update styles and rules from a local resource (like shared folder) or local repository (Gitlab self-hosted instance), not [a public one](https://github.com/errata-ai/styles/blob/master/library.json)?

If this feature is implemented, I'll be able to update rules immediately for all my mates in our company.

I think this feature can be useful for enterprise customers.

Thank you!

**Comment by jdkato** [comment]
The next release will allow you to set custom, project-specific `StylesPath`s, so this will be possible with shared folders.

**Comment by jdkato** [comment]
The new release was published today. The new custom `StylesPath` feature is discussed here: https://errata-ai.github.io/vale-server/docs/sync.
