### ISSUE TITLE
Missing automatic updates

### ISSUE THREAD

**Issue by tperry-r7** [errata-ai/vale-server#18]
My version of Vale Server 1.4 is missing the checkbox to automatically look for updates. I've done a restart of my system and of Vale. https://errata-ai.github.io/vale-server/docs/ui#general

<img width="497" alt="Screen Shot 2020-06-08 at 8 33 36 AM" src="https://user-images.githubusercontent.com/54866039/84036468-dc87d500-a962-11ea-9f25-fd47e1fc1157.png">

**Comment by jdkato** [comment]
This is a feature of v1.5, which was released recently. The docs have a version selector that you can use to see the older information, if needed.
