### ISSUE TITLE
Windows protected your PC. Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

### ISSUE THREAD

**Issue by brest-amzn** [errata-ai/vale-server#20]
Trying to install Vale Server on Windows 10 gives this error.

Windows protected your PC
Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

https://answers.microsoft.com/en-us/protect/forum/all/who-to-contact-to-get-our-software-filed-as-safe/62d5f3eb-09d8-467b-8e44-97aa25ec2858

Can you submit Vale so it no longer is flagged? 
https://www.microsoft.com/en-us/wdsi/filesubmission

Otherwise this may cause concerns for our (and other) IT departments.

**Comment by jdkato** [comment]
The malware analysis link isn't relevant to this warning and submitting Vale Server won't stop the warning from being shown (as discussed in the linked Microsoft Community post). As is, you can click "More info" -> "Run anyway" to proceed with the installation.

As far as "solutions" go, there are only two ways to stop seeing this warning:

1. Amass enough trust organically by getting 3,000+ downloads (this is a commonly cited figure, but I'm not sure what the exact number is); or

2. Pay for "trust" by buying an EV Code Signing certificate.

I'll look into option number (2) for the next release.
