### ISSUE TITLE
Check for updates.... does not work on Windows 10

### ISSUE THREAD

**Issue by brest-amzn** [errata-ai/vale-server#29]
I am trying to update to the new version of Vale server (1.5 to 1.6) by using the "check for updates..." menu item.

https://headwayapp.co/errata-ai-release-notes/vale-server-v1-6-161693

The update downloads, but I get an error when it tries to install.
Screenshot is attached.

I am on Windows 10 64 bit. 
![error](https://user-images.githubusercontent.com/55214086/89691028-d0fe4f00-d8bc-11ea-9311-55a20a50876b.PNG)

**Comment by jdkato** [comment]
Thanks for the report.

Does your Windows account have administrator privileges?

**Comment by jdkato** [comment]
> Does your Windows account have administrator privileges?

I'm nearly certain this is the issue: If you start Vale Server from the start menu with "Run as administrator," you'll be able to complete the download.

The next release will automatically ask for this permission upon starting an update.

**Comment by brest-amzn** [comment]
Thanks. I confirmed that using "Run as administrator" worked.
