### ISSUE TITLE
Produce aggregated "score" and compare against a baseline

### ISSUE THREAD

**Issue by brest-amzn** [errata-ai/vale-server#37]
It would be great if Vale could produce an aggregated "score" of the errors on each file you are scanning. Users would also define a baseline in the configuration file.

For example:
- errorBaseLine: 5
- warningBaseLine: 10
- infoBaseLine: 20
 
After a scan, Vale would compare the # of errors in your files against your baseline and produce a percentage or a "score" of how well your document is doing. For example your baseline score could be 80% error free. 

With this feature, Vale could help drive actionable goals / KPIs. For example, get all documents above a 80% by the end of the year.

You could even display them in the dashboard with Vale Server.

**Comment by brest-amzn** [comment]
Awesome. This will be very useful and really adds value to Vale. Thanks!

**Comment by jdkato** [comment]
Quick update here: this is still in the works -- it's going to be implemented as a "Summary" page that replaces the existing "Studio" page (which was recently moved to a standalone app for *both* Vale and Vale Server users -- see https://vale-studio.errata.ai/).

I should have some demo / prototype screenshots next week.

**Comment by jdkato** [comment]
The first iteration of this feature is now available in v1.9 -- see https://docs.errata.ai/vale-server/gui#summary. Integration with the editor clients (VS Code, Atom, Sublime) is on the way too.
