### ISSUE TITLE
LanguageTool does not working Vale Server 1.8

### ISSUE THREAD

**Issue by brest-amzn** [errata-ai/vale-server#38]
Environment:
- Windows 10 64 bit
- languageTools 5.0
- Vale server 1.8
- Atom 1.5.1
- vale-server atom client 1.7.1

I am trying to run the new LanguageTool background process and it does not work as expected. I have followed your instructions [here](https://docs.errata.ai/vale-server/add-ons/languagetool).  

I am using the open source [JDK](https://jdk.java.net/15/), not the commercial version of Java. Maybe that is why? We need to use JDK because Java now requires a license for commercial use.

I checked the logs, the server starts properly. However, when I go to localhost:7778/v2/check I get this error message.
`Error: Missing 'text' or 'data' parameter`

<img width="499" alt="pic2" src="https://user-images.githubusercontent.com/55214086/93390562-beaff300-f822-11ea-9c32-8da518dd6839.PNG">

<img width="498" alt="set-up" src="https://user-images.githubusercontent.com/55214086/93390956-5ad9fa00-f823-11ea-862a-15d41fa5a4f9.PNG">

Note: I also tried linking to other JDK install paths, such as just the root folder and \bin, but they also do not work (in fact, I do not even get the error response if I change the path).

**Comment by jdkato** [comment]
It actually appears to be working (or, at least, running): you're not supposed to navigate to the URL directly; Vale Server passes text from its clients (VS Code, Atom, etc.) to this endpoint in the background. If you'd like to verify this, you can define the required parameters yourself: http://localhost:7778/v2/check?text=hey&language=en-US.

Are you not receiving results from your editor?

**Comment by brest-amzn** [comment]
I am not receiving any results in my editor. I tried both atom and sublime. The regular linting is still working as expected.

notes. 

- I have added LanguageTool to my config file. `BasedOnStyles =  LanguageTool`
- Vale shows the LanguageTool folder under the "styles" tab.

**Comment by brest-amzn** [comment]
Update. It is working. I pasted in more text/examples from the language tool website.

I must have inadvertently been testing unsupported rules
https://docs.errata.ai/vale-server/add-ons/languagetool#usage.

"Currently, only rules listed in the MISC, GRAMMAR, CONFUSED_WORDS, and TYPOS categories are enabled."
