### ISSUE TITLE
Vale plugin for IntelliJ

### ISSUE THREAD

**Issue by wouter-veeken** [errata-ai/vale-server#39]
As requested by @ChrisChinchilla, here's an issue to request a Vale plugin for IntelliJ with "squiggly lines" functionality.

Background: IntelliJ is widely used among devs I work with and they're more likely to follow my Vale styles if they get real-time feedback in their chosen IDE.

**Comment by jillesvangurp** [comment]
> Intellij is an edge case as it's not open source, is commercial, but also has free versions, and the platform for creating extensions is monetizable, but open to anyone etc. I'm not sure myself

The community edition is licensed under the Apache license: https://github.com/JetBrains/intellij-community and freely available. They also have community editions of some of their other products like pycharm.

**Comment by jillesvangurp** [comment]
Two ways to run vale in intellij:

1) in preferences, tools, external tools add a configuration for vale.
I used this as the command line arguments:
`--config /Users/jillesvangurp/.vale.ini --output line --sort --relative $FilePathRelativeToProjectRoot$`
and `$ProjectFileDir$` as the working directory. I did not manage to get the output filters to work but instead rely on the Awesome Console plugin for this.

2) execute via a gradle task. Note, lots of room for improvement in this but it works. You can run the gradle task in intellij. I think there's a dedicated vale plugin for gradle as well that you could use instead.

```
tasks.register("vale") {
    doLast {
        project.exec {
            commandLine("vale", "--config", "/Users/jillesvangurp/.vale.ini", "--output", "line", "--sort", "--relative", "README.md")
        }
    }
}
```

In both cases, I use the Awesome Console plugin that turns the file names + line numbers in the output into clickable links. The only thing missing is for this to pick up the warnings and highlight them in the file.

**Comment by ChrisChinchilla** [comment]
Hey @jillesvangurp fancy seeing you here 👋 . I am actually going to finish my plugin writing guide tomorrow, and then hopefully anyone who wants to pick this up can use that to help them. I will also add your steps above to the docs as an integration guide.

**Comment by ChrisChinchilla** [comment]
Here's that draft guide - https://github.com/errata-ai/vale-server/pull/42

**Comment by ChrisChinchilla** [comment]
And finally @jillesvangurp you mention a grade plugin, but I couldn't find it. Any link?

**Comment by jillesvangurp** [comment]
@ChrisChinchilla https://github.com/jjaderberg/vale-gradle-plugin this one and looks unmaintained.

**Comment by ChrisChinchilla** [comment]
Hmm @jillesvangurp but it still worked for you?

**Comment by ChrisChinchilla** [comment]
Could be good just to update that as a basis perhaps 🤔

**Comment by jillesvangurp** [comment]
Did not try it. I don't really need gradle support currently.

**Comment by ChrisChinchilla** [comment]
I'll add it anyway, this issue is still open for anyone wanting to make a "better" plugin.

**Comment by tarasweeney** [comment]
@jillesvangurp @ChrisChinchilla @jdkato 
Hi! I am working in IntelliJ. I have Vale set up and working in Terminal (Mac).
I added the Awesome Console plugin.
Then, I tried adding the external tool:

Arguments: --config /Users/<my dir>/.vale.ini --output line --sort --relative $/Users/<my dir>/IdeaProjects/<myrepoinfo>$
Working directory: $ProjectFileDir

However, I can't seem to get further than this to get any validation back. 
1. Maybe my setup is incorrect?
2. Maybe I don't know how to use the Awesome Console and External Tool. I tried going to Tools > External Tools > Vale, but nothing happens.

**Comment by jillesvangurp** [comment]
Sorry not really using this currently. I'd recommend checking out the Jetbrains Grazie plugin that @ChrisChinchilla recently covered on his youtube channel. It integrates vale and a few other things. https://www.youtube.com/watch?v=Y1QvrsH-Dk4

**Comment by tarasweeney** [comment]
Got it! To run Vale in IntelliJ:

1. Install the [Awesome Console](https://plugins.jetbrains.com/plugin/7677-awesome-console).
2. Go to IntelliJ IDEA > Preferences > Tools > External Tools.
3. Add Vale and enter the following:
For Arguments: --config /Users/<your user directory>/.vale.ini --output line --sort --relative $FilePathRelativeToProjectRoot$
For Working directory: $ProjectFileDir$
4. Define a keyboard shortcut or specify an icon for Vale.
5. Open any file (I am using .adoc) and use your keyboard shortcut, toolbar icon, or go to Tools > External Tools > Vale. The results are shown in the Run window.

**Comment by ChrisChinchilla** [comment]
Hmm, well it looks like the guide that I wrote has vanished from the website and replaced with a link to Grazie anyway, so I think this is probably all closed now as that plugin wraps Vale in a kind of way. @jdkato ?

**Comment by jdkato** [comment]
@ChrisChinchilla, I've [updated the page](https://vale.sh/docs/integrations/jetbrains/) to include both a description of Grazie and a slightly updated version of your guide.
