### ISSUE TITLE
Document creating integration extensions

### ISSUE THREAD

**Issue by ChrisChinchilla** [errata-ai/vale-server#40]
A couple of people have asked how to create Vale extensions, while we can't really document creating extensions for various platforms, documenting the endpoints (Server) and CLI command configuration might be a good idea. Happy to handle this, so assign to me…

**Comment by rachfop** [comment]
I think this can be closed:
https://github.com/errata-ai/vale-server/pull/42 and [Creating a plugin](https://github.com/errata-ai/vale-server/blob/master/website/docs/common/creating-plugin.md).
