### ISSUE TITLE
Vale Sever no longer works after updating to Vale Server 1.9 

### ISSUE THREAD

**Issue by brest-amzn** [errata-ai/vale-server#43]
Vale no longer launches.  

I get the following error message after installing Vale Server 1.9 (see image).
I tried uninstalling Vale completely and reinstalling. I still get the error.
<img width="540" alt="error" src="https://user-images.githubusercontent.com/55214086/100007282-b3c49200-2d80-11eb-889e-42e2fafa86bf.PNG">

Notes:
I am on Windows 10 64 bit.
I used the .exe file that was supplied in the auto-generated update email (I did not use the "check for updates" button in the Vale  taskbar menu.

**Comment by jdkato** [comment]
Thanks for the report.

I recently switched to a new auto-updater (WinSparkle) and I think the installer provided through Gumroad was failing to provide the `.dll`. 

I've manually updated the installation links and it should now be working.
