### ISSUE TITLE
Vale Server upgrade is unsuccessful

### ISSUE THREAD

**Issue by dfinr** [errata-ai/vale-server#48]
Platform: Windows 10

Upgrading from version 1.10.0 to 1.11.10.

I've tried the automatic upgrade twice, and also downloaded [the full package](https://errata.ai/vale-server/#purchase). In both cases the wizard ran without error, but the software was not updated. When Vale Server restarted at the end of the installation process, it immediately reported that an update was available. 

I have not attempted a full uninstall/reinstall because I am unsure how this impacts my license activation status. Attached is the directory listing for `C:\Program Files (x86)\Vale Server` after the upgrade process.
[ValeDirListing.txt](https://github.com/errata-ai/vale-server/files/5754510/ValeDirListing.txt)

**Comment by jdkato** [comment]
This should be fixed now.

**Comment by dfinr** [comment]
My upgrade succeeded. Thank you.
