### ISSUE TITLE
Refine browser experience

### ISSUE THREAD

**Issue by jdkato** [errata-ai/vale-server#5]
With the first release of our Chrome extension officially available, there are some implementation details we should figure out:

- [x] Determine when we should activate (currently, it's done on a per-tab, opt-in basis).
    - We now (as of `v1.3.0`; currently in review) activate automatically.
- [ ] Determine how we should handle markup. Idea: Allow users to specify format on a URL-specific basis (e.g., `github.com` -> Markdown).
- [ ]  Support in-text highlighting in `[contenteditable]` elements.
- [ ] Add support other WebExtensions-compatible browsers (e.g., Firefox, Opera, etc.)

**Comment by brandonkal** [comment]
Integration with https://github.com/akahuku/wasavi would be a valuable improvement for developers.

**Comment by jdkato** [comment]
Thanks for the suggestion.

I'm currently working on releasing Vale Server v1.3 (should be a few days), which includes a number of new features (including LanguageTool integration). But, after that, I intend to work on releasing a new version of the Chrome extension -- so, I'll look into this.

**Comment by jdkato** [comment]
The extension has been entirely re-written and now offers a much more refined experience -- once it's out of review, a new version of Vale Server will be released and I'll cover the new features in more detail.
