### ISSUE TITLE
Make dashboard link based off of user's port number

### ISSUE THREAD

**Issue by rachfop** [errata-ai/vale-server#50]
In the preference menu, under Style, the dashboard link is hard-coded to `http://localhost:7777/styles.html` but it should be whatever the user has imported into the port number. 

Not a huge deal, but if my localhost is set to 8888, and I click the dashboard link from this sentence: 

> All of your installed styles will appear below. Double-click a style to inspect its contents. See the **dashboard** for more information.

My browser will not take me to my port I have specified in the Advanced menu.

**Comment by jdkato** [comment]
Thanks for the report. It will be fixed in the next release.
