### ISSUE TITLE
Vale Server catches some errors, but not style issues.

### ISSUE THREAD

**Issue by rolfedh** [errata-ai/vale-server#56]
I've installed Vale Server and the Vale Client in VS Code. I've created a "test" project and installed all of the default styles. When I write intentionally faulty text, Vale flags errors like "the the", but doesn't seem to flag style issues. For example, I introduced phrases like this, which should generate a recommendation from Google style's contractions.yml rule:
```
We are not going to give the the man... 
We aren't going to give man...
```
In other words, it seems like I'm not getting the styles to work. 

I've read the docs but can't figure out what step I'm missing to make styles work. Can you help?

Contractions.yml:
```
extends: substitution
message: "Feel free to use '%s' instead of '%s'."
link: 'https://developers.google.com/style/contractions'
level: suggestion
ignorecase: true
action:
  name: replace
swap:
  are not: aren't
  cannot: can't
  could not: couldn't
  did not: didn't
  do not: don't
  does not: doesn't
  has not: hasn't
  have not: haven't
  how is: how's
  is not: isn't
  it is: it's
  should not: shouldn't
  that is: that's
  they are: they're
  was not: wasn't
  we are: we're
  we have: we've
  were not: weren't
  what is: what's
  when is: when's
  where is: where's
  will not: won't
```

**Comment by rachfop** [comment]
@rolfedh I used https://vale-studio.errata.ai/ to the contraction rules, and they were applied to those sentences as expected.

**Comment by rolfedh** [comment]
Thanks, @rachfop. I'm sure the rules work, I'm just not sure how to set up my system so it applies the Google style rules to a simple test.md file. Do you have any suggestions?

**Comment by jdkato** [comment]
Could you please share your project configuration (`.vale.ini`)?

**Comment by rolfedh** [comment]
Thanks for asking, @jdkato. In the Vale Server preferences, looking at Project, I see 
```
# This is an example configuration file.

StylesPath = "/home/rdlugyhe/.local/share/errata-ai/Vale Server/styles"

# The minimum alert level to display.
#
# Accepted options are suggestion, warning, or error.
MinAlertLevel = suggestion

[*]
# List of styles to load.
BasedOnStyles = Vale
```
However, when I search my system for .vale.ini, I find various .vale.ini files but not one with these contents. 

From finding these files and reading the Vale (not Vale Server) docs, it becomes clear that I must _create_ `.vale.ini` in the root directory of my doc repo directory. This repo directory is also commonly referred to as a "project" directory.

The Vale Server docs don't mention `.vale.ini` until the [Configuration](https://docs.errata.ai/vale-server/concepts/config) topic. There, the phrasing is ambiguous and seems to imply that it might already exist somewhere. That potential misunderstanding is supported by the ambiguity of the Project tab in the Vale Server preferences.

For me, this combination of docs and UI raises questions like "Where does the file in that Project tab live? Could we identify that information as the contents of a .vale.ini file. Should the Projects tab display the paths of the various projects? Can I use this Project tab to create an `ini` file in the root directory of a doc repo?"

Although the docs are concise and accurate, I'd like to be up and running by the time I finish the getting started and usage topics. Perhaps a tutorial involving the sample repository you provide in the Vale usage topic would help.

I hope sharing this beginner's perspective is useful. I'll be glad to help revise or improve the documentation to address the needs of beginning users.

**Comment by rolfedh** [comment]
Update: When I open README.md from /home/rdlugyhe/vale-boilerplate/ in VS Code, Vale flags "is is" on line 27 with `'is' is repeated!Vale Server(Vale.Repetition)` but not "extremely" on line 13.

**Comment by jdkato** [comment]
You don't need to create a `.vale.ini`; you just need to enable the styles that you want to be active.

As you mentioned in your first post, you were getting results from the `Vale` style ("the the", etc.), but not `Google`. That's because `Vale` was the only style active in your project's configuration (`BasedOnStyles = Vale`). If you change your Project's configuration (from the Vale Server Preferences tab) to the following, it should work as expected:

```ini
# This is an example configuration file.

StylesPath = "/home/rdlugyhe/.local/share/errata-ai/Vale Server/styles"

# The minimum alert level to display.
#
# Accepted options are suggestion, warning, or error.
MinAlertLevel = suggestion

[*]
# List of styles to load.
BasedOnStyles = Vale, Google
```

> Does this Project serve as a sort of global configuration file that is independent of the `.vale.ini` file in the root folder of the doc repo?

Yes, depending on what [mode you're using](https://docs.errata.ai/vale-server/usage#choosing-a-mode) (see below).

> Does one override the other?

`Server` mode will only use the active project (Vale Server Preferences tab); `Command Line` mode will only use local Vale configurations (`.vale.ini` in a parent directory). `Compatibility` mode combines the two according to certain rules (see the link above).

These docs have been published for a while, but were accidentally removed in a recent PR. Sorry if that contributed to the confusion.

---
> Where does the file in that Project tab live?

Since you can have many such project configurations (and switch between them using the context menu), it doesn't have a specific directory location like configurations for Vale (the CLI tool). Instead, Vale Server manages these configurations internally.

> Can I use this Project tab to create an ini file in the root directory of a doc repo?

No, Vale Server is self-contained in the sense that its Project configurations don't need to be located in a certain root directory. They'll work with any file, potentially even overriding the local configuration (again, depending on the mode).

**Comment by rolfedh** [comment]
I got it working by adding `write-good` to the selected project in Vale Server preferences. Now, VS Code is flagging "extremely" in REAME.md. 

During that process, I had trouble saving the change to the project. On my first attempt,  I selected Quit Vale Server and restarted the server: This didn't save the change. However, on my second attempt, I clicked the Restart Server button on the Advanced tab window in Preferences, and it saved the changes. I recommend adding a Save button to the Project tab window so users can explicitly save and apply changes to the project.

This clears up my confusion about where/how to configure Vale Server > Preferences > Project. It also makes clear that these project settings override the .vale.ini file in the root directory of the docs. 

Now, if my repo has a .vale.ini file, I expect I should create a new project in vale server and paste the contents of that .ini file into the project, right? Or is there a better way to do this?

**Comment by jdkato** [comment]
> During that process, I had trouble saving the change to the project.

Currently, Vale Server saves on edit -- so, if you simply close the Preferences panel, your changes will be preserved. You don't need to quit or restart to save the changes (doing the former likely interrupted the saving process). I'll make this more clear in the documentation.

> Now, if my repo has a .vale.ini file, I expect I should create a new project in vale server and paste the contents of that .ini file into the project, right? Or is there a better way to do this?

It depends.

- If you'd like to use this `.vale.ini` configuration with multiple repos, I'd make it a Vale Server project.

- If this `.vale.ini` configuration is specific to the repo or needs to be remotely accessible (such as for running `vale` on a CI server),  I'd switch Vale Server into `Command Line` mode while editing files in the repo so you don't have to duplicate the configuration.

**Comment by rolfedh** [comment]
Excellent. Thank you for your help on this! I think we can close this issue.
