### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by ChrisChinchilla** [errata-ai/vale-server#61]
I took Server for another spin today and was hit by some errors I've not seen before. In VSCode i see the following error in Dev tools - `Vale Server could not connect: StatusCodeError: 400 - {"error":"missing 'alert'"}.` And also I get a connection error for the dashboard in browsers, and in the GDocs extension.

Any ideas? I do have a bunch of blockers, could they be causing an issue?

**Comment by jdkato** [comment]
What does the console under (Vale Server's) `Preferences -> Advanced` say?

**Comment by ChrisChinchilla** [comment]
I don't see console, but I see "API status"?

```
Running.

Server is available at http://localhost:7777 (bind address 127.0.0.1).
```

**Comment by jdkato** [comment]
I'm not totally sure.

The API status indicates that the server is running correctly, but the connection errors clearly indicate otherwise (especially for the dashboard, which means it's likely not an issue with VS Code/Google Docs specifically).

What do you mean by "blockers"?

**Comment by ChrisChinchilla** [comment]
@jdkato I use Adguard, it doesn't block any other local servers, so I don't think it's that. My only other thought is maybe that another local server is using the same port, but then I would have though that Vale Server would say so

**Comment by ChrisChinchilla** [comment]
@jdkato And now it works 🤷
