### ISSUE TITLE
Having connection issues with Vale Server on Mac 

### ISSUE THREAD

**Issue by technicaltidbits** [errata-ai/vale-server#62]
I am running into this error when I try to use Vale Server on my Mac (macOS 10.14.6):

```
Vale Server could not connect: RequestError: Error: read ECONNRESET
```

Things I've done to try to resolve the problem:
* Updated to the latest version of Vale Server (1.12.0)
* Restarted my Mac
* Restarted VS Code
* Uninstalled and reinstalled VS Code extension
* Quit Vale Server application

When I go to `Preferences > Advanced`, I see the message `Running. Server is available at http://localhost:7777 (bind address 127.0.0.1)`, so not sure why it isn't working.

**Comment by jdkato** [comment]
This looks like https://github.com/errata-ai/vale-vscode/issues/37, which I was never able to reproduce.

If possible, could you provide your active configuration (Preferences -> Projects) and a sample file that causes the error?

**Comment by deanna-cs** [comment]
@jdkato Sorry for my late response. The problem was actually my configuration file. I had it set to `[*md]`. Apologies for the trouble.
