### ISSUE TITLE
Vale Server is asking for a license but I want to try it first

### ISSUE THREAD

**Issue by mayela** [errata-ai/vale-server#64]
Hi everyone,

I installed Vale Server on a VM(ubuntu 20.10) but when I run it, it is asking me for a license, first I like to try it. There is a specific trial license I should configure?

Thanks in advance for your help!

![photo5003772947680307560](https://user-images.githubusercontent.com/665952/131574333-0a01da4c-d6e0-4f4a-8f50-5577f5b5d292.jpg)

**Comment by jdkato** [comment]
Hi,

There's no trial license key -- the free trial starts automatically. Unfortunately, we don't currently support trials on VMs.

**Comment by mayela** [comment]
Thank you so much for your response!
