### ISSUE TITLE
Unable to add license key in the UI

### ISSUE THREAD

**Issue by mjang** [errata-ai/vale-server#71]
I try to add a license key, using the instructions in https://docs.errata.ai/vale-server/install#activation

When I see the Enter License window, I'm unable to enter any characters.

Workaround: set up the License key in the automated file described in https://docs.errata.ai/vale-server/install#automated

Vale Server Version: 1.12.0
MacOS Version 11.6

**Comment by jdkato** [comment]
I'm going to assume this can be closed, but feel free to comment further if the above explanation didn't work for you.
