### ISSUE TITLE
Updating Vale CLI binary doesn't work

### ISSUE THREAD

**Issue by ChrisChinchilla** [errata-ai/vale-server#72]
I tried to update the binary installed by Homebrew from selecting via an alias and a direct patch to the homebrew installation and in every case I get this error message (I have the latest version).

<img width="532" alt="Screen Shot 2021-11-11 at 16 39 11" src="https://user-images.githubusercontent.com/42080/141326232-c4fd48e4-5686-4731-82d5-e2fd39fad619.png">

**Comment by jdkato** [comment]
Yeah, it should work with just the Homebrew installation path, but I can reproduce the issue.

I'll release a new version of Vale Server next week that fixes this. I'll also add an option for simply using the version of Vale from the active `$PATH`.
