### ISSUE TITLE
License key no longe recognised

### ISSUE THREAD

**Issue by anthillsocial** [errata-ai/vale-server#75]
I purchased a licence key 25th October 2021 and everything has been working fine (on Arch Linux) until Vale Server (VS) stopped recognising the licence key I had purchased. 

1. I deleted the key.
2. Restarted VS: Vale-Server-1.12.0-linux.AppImage. 
3. Get a prompt to "purchase a licence key" (which I have). 
4. Click 'ok'.
5. Select 'enter licence' and do so in the prompt.
6. Get a 'Stopped (invalid response; 503)' message. 

I also tried double checking my license details using the 'licence key lookup service' at https://app.gumroad.com/license-key-lookup but it doesn't recognise my contact details and I haven't got a response from the email provided. 

Can you please advise? 
Thanks
Tom

**Comment by jdkato** [comment]
Please update to v1.13.0. You can find the download in your Gumroad account (you should also have received an email with the updated version).

**Comment by jdkato** [comment]
I'm closing this as resolved, but feel free to comment further if you still have questions.
