### ISSUE TITLE
Installing Vale Server 2.0 [Linux/Fedora]: GTK and system tray errors

### ISSUE THREAD

**Issue by michaelryanpeter** [errata-ai/vale-server#79]
I am trying to install Vale Server on Fedora 34. When I launch the Vale Server AppImage from the terminal, I get the error messages below in the shell. Also, an alert window pops up with the message: "Vale Server: I couldn't detect any system tray on this system."

I've tried moving the Vale binary between my user and root `$PATH`. Any help would be appreciated. Thanks!

```
Gtk-Message: 12:58:13.082: Failed to load module "xapp-gtk3-module"
Gtk-Message: 12:58:13.131: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:58:13.132: Failed to load module "pk-gtk-module"
Gtk-Message: 12:58:13.132: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:58:13.132: Failed to load module "pk-gtk-module"
```

**Comment by ChrisChinchilla** [comment]
@michaelryanpeter Stupid question, but did you follow the instructions for linux? I just installed a VM of Fedora to try and couldn't even get as far as you did, but I suspect that's because I am running on ARM, though I am not certain…

**Comment by aireilly** [comment]
For F35, try this: 

1. Install the gnome extension for tray icons: https://extensions.gnome.org/extension/2890/tray-icons-reloaded/

2. Create a Vale system service.

		sudo mv Vale-Server-2.0.0-linux.AppImage /usr/local

		chmod +x /usr/local/Vale-Server-2.0.0-linux.AppImage

3. Autostart the Vale server on reboot - create a $HOME/.config/autostart/vale.desktop file with the following, exec pointing to where you put the AppImage:

		[Desktop Entry]
		Type=Application
		Name=Vale
		Exec=/usr/local/Vale-Server-2.0.0-linux.AppImage

**Comment by michaelryanpeter** [comment]
@aireilly Your instructions worked. I did have to install GNOME [Extension Manager](https://github.com/mjakeman/extension-manager).

@ChrisChinchilla I haven't been able to install Vale via Brew, so I always download the binary and move it to my `$PATH`, but otherwise the Vale CLI works consistently and without issue.
