### ISSUE TITLE
Unable to use Google Docs Plugin

### ISSUE THREAD

**Issue by mjang-cobalt** [errata-ai/vale-server#83]
The Google Docs plugin worked before... (It's quite possible this is a Mac issue, as it worked fine a few days ago, with the same software versions)

Environment: MacOS Monterrey (12.1)
Vale Server 2.0.0
Vale CLI 2.14.0

Process:

1. I start Vale Server from the MacOS bottom taskbar 
2. Per the doc, I run `open -a "Vale Server"`
3. I select the Vale Server icon > Preferences > Advanced
4. I select Restart Server
5. I access the dashboard via http://localhost:777
6. I see that `_vale` is "not found"
7. I try reinstalling vale (using `brew upgrade vale` and `brew uninstall vale` followed by `brew install vale`)
   - Reinstalling vale no longer helps

Possibly related: https://github.com/errata-ai/vale-server/issues/80. I do see the `vale` binary in my $PATH, specifically in `/usr/local/bin`.

**Comment by jdkato** [comment]
The only step you need to do is (2).

The process is (1) quit the application and (2) start it by running `open -a "Vale Server"` from your terminal.

The `open -a` step should *replace * clicking the app icon from the taskbar.

**Comment by mjang-cobalt** [comment]
Thanks @jdkato. That works! I've suggested a clarification in PR #5: https://github.com/errata-ai/docs/pull/5

**Comment by theletterf** [comment]
Guess this one can be closed, @mjang-cobalt ?

**Comment by mjang-cobalt** [comment]
Now that https://github.com/errata-ai/docs/pull/5#issuecomment-1049097366 is merged, I think we can close this issue.
