### ISSUE TITLE
Resource Suggestion: a tutorial on using vale with neovim

### ISSUE THREAD

**Issue by Bhupesh-V** [errata-ai/vale-server#90]
Hey, I recently published [Writing like a pro with vale & neovim](https://bhupesh.me/writing-like-a-pro-with-vale-and-neovim/) which covers how to use NeoVim with vale. I hope it helps the community.

**Comment by jdkato** [comment]
Thanks!

I've been recently working on building an index of [searchable resources](https://vale.sh/docs/) and I've included your post. If you write any more, feel free to submit to the new [library repo](https://github.com/errata-ai/library).
